# Generated by Django 3.2 on 2023-08-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coverimage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='projectdetailimage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
