# Generated by Django 3.2 on 2023-08-23 19:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('services', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('details', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
