# Generated by Django 3.2 on 2023-08-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='coverimage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
